spawn_coords:
  x: 2.5
  y: 67.5
  z: -5.5
messages:
  teleport_to_spawn: "<gold>Teleporting to spawn..."
  website: "<red><b>Visit the website<br><click:open_url:https://www.rabbit-network.net>www.rabbit-network.net"
  nv_add: "<blue>You now have night vision."
  nv_remove: "<blue>You removed you night vision effect."
  not_a_player: "<dark_red>You have to be a player to use that command."
  first_join_message: "<red><bold>Welcome %player% to the server for the first time!"
  join_message: "<gray>%player% joined the game."
  leave_message: "<rainbow>%player% has left the game."
  config_reload: "<green>Config has been reloaded."
broadcast:
  broadcast_delay: 60 # in seconds
  message_1: <gold>Annoucement.