name: Rabbit
version: 'rabbit-network'
main: me.rabbittv.rabbit.Rabbit
api-version: '1.21'
commands:
  spawn:
    description: Get teleported to spawn
    usage: /<command>
  nv:
    description: Get the night vision effect
    usage: /<command>
    aliases: nightvision
  website:
    description: Send the website the the player
    usage: /<command>
    aliases: buy